version: '3.8'

services:
  # MongoDB 데이터베이스
  mongodb:
    image: mongo:7.0
    container_name: ecommerce-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerce_ai
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce-network

  # FastAPI 백엔드
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=ecommerce_ai
      - DEBUG=True
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
    networks:
      - ecommerce-network

  # React + Vite 프론트엔드
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - ecommerce-network
    stdin_open: true
    tty: true

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mongodb_data:
